# Generated by Django 3.2.5 on 2021-07-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('http_proxy', '0002_auto_20210710_2030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestMonitor',
            new_name='DailyRequestMonitor',
        ),
        migrations.RemoveIndex(
            model_name='dailyrequestmonitor',
            name='http_proxy__request_de8994_idx',
        ),
        migrations.AddIndex(
            model_name='dailyrequestmonitor',
            index=models.Index(fields=['request_model', '-date'], name='http_proxy__request_915d54_idx'),
        ),
    ]
