# Generated by Django 3.2.5 on 2021-07-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('http_proxy', '0004_auto_20210711_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propublicarequest',
            options={'verbose_name': 'ProPublica request'},
        ),
        migrations.AddIndex(
            model_name='propublicarequest',
            index=models.Index(fields=['endpoint', '-sent_on'], name='http_proxy__endpoin_346fc0_idx'),
        ),
    ]
