# Generated by Django 3.2.5 on 2021-07-13 02:08

from django.db import migrations, models
import http_proxy.models


class Migration(migrations.Migration):

    dependencies = [
        ('http_proxy', '0007_auto_20210712_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propublicarequest',
            name='granted',
            field=models.BooleanField(default=http_proxy.models.DailyRequestManager.request_grant, editable=False),
        ),
    ]
