# Generated by Django 3.2.5 on 2021-07-13 03:18

from django.db import migrations, models
import http_proxy.models


class Migration(migrations.Migration):

    dependencies = [
        ('http_proxy', '0009_auto_20210712_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrequestmonitor',
            name='date',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='propublicarequest',
            name='granted',
            field=models.BooleanField(default=http_proxy.models.DailyRequestManager.request_grant, editable=False),
        ),
    ]
