# Generated by Django 3.2.5 on 2021-07-14 00:51

from django.db import migrations, models
import http_proxy.models


class Migration(migrations.Migration):

    dependencies = [
        ('http_proxy', '0010_auto_20210712_2018'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='propublicarequest',
            name='http_proxy__endpoin_346fc0_idx',
        ),
        migrations.AlterField(
            model_name='propublicarequest',
            name='granted',
            field=models.BooleanField(default=http_proxy.models.DailyRequestManager.request_grant, editable=False),
        ),
        migrations.AddIndex(
            model_name='propublicarequest',
            index=models.Index(fields=['endpoint', 'http_method'], name='http_proxy__endpoin_36dd1f_idx'),
        ),
        migrations.AddIndex(
            model_name='propublicarequest',
            index=models.Index(fields=['-created_on'], name='http_proxy__created_45f836_idx'),
        ),
        migrations.AddIndex(
            model_name='propublicarequest',
            index=models.Index(fields=['-sent_on'], name='http_proxy__sent_on_213f3f_idx'),
        ),
    ]
