# Generated by Django 3.2.5 on 2021-07-14 02:37

from django.db import migrations, models
import http_proxy.models


class Migration(migrations.Migration):

    dependencies = [
        ('http_proxy', '0011_auto_20210713_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='propublicarequest',
            name='response',
            field=models.JSONField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='propublicarequest',
            name='granted',
            field=models.BooleanField(default=http_proxy.models.DailyRequestManager.request_grant, editable=False),
        ),
    ]
