# Generated by Django 3.2.5 on 2021-07-14 02:44

from django.db import migrations, models
import http_proxy.models


class Migration(migrations.Migration):

    dependencies = [
        ('http_proxy', '0012_auto_20210713_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propublicarequest',
            name='granted',
            field=models.BooleanField(default=http_proxy.models._propublica_request_grant, editable=False),
        ),
    ]
