# Generated by Django 3.2.5 on 2021-07-17 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('http_proxy', '0012_alter_propublicarequest_granted'),
        ('http_proxy', '0013_alter_propublicarequest_granted'),
    ]

    operations = [
    ]
