# Generated by Django 3.2.5 on 2021-07-17 04:58

from django.db import migrations, models
import http_proxy.models


class Migration(migrations.Migration):

    dependencies = [
        ('http_proxy', '0014_merge_20210716_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propublicarequest',
            name='granted',
            field=models.BooleanField(default=http_proxy.models._propublica_request_grant, editable=False),
        ),
    ]
