# Generated by Django 3.2.5 on 2021-07-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('http_proxy', '0003_auto_20210711_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrequestmonitor',
            name='date',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='dailyrequestmonitor',
            name='grant_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='dailyrequestmonitor',
            name='request_model',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='dailyrequestmonitor',
            name='sent_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='propublicarequest',
            name='endpoint',
            field=models.URLField(editable=False),
        ),
        migrations.AlterField(
            model_name='propublicarequest',
            name='granted',
            field=models.BooleanField(editable=False),
        ),
        migrations.AlterField(
            model_name='propublicarequest',
            name='http_code',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='propublicarequest',
            name='http_method',
            field=models.CharField(choices=[('GET', 'Get')], editable=False, max_length=7),
        ),
        migrations.AlterField(
            model_name='propublicarequest',
            name='sent_on',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
