# Generated by Django 3.2.5 on 2021-07-13 03:11

from django.db import migrations, models
import django.utils.timezone
import http_proxy.models


class Migration(migrations.Migration):

    dependencies = [
        ('http_proxy', '0008_alter_propublicarequest_granted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrequestmonitor',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='propublicarequest',
            name='granted',
            field=models.BooleanField(default=http_proxy.models.DailyRequestManager.request_grant, editable=False),
        ),
    ]
