# Generated by Django 3.2.5 on 2021-07-10 04:40

from django.db import migrations, models
import senate.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Senator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('suffix', models.CharField(max_length=20, null=True)),
                ('date_of_birth', models.DateField()),
                ('in_office', models.BooleanField()),
                ('party', models.CharField(max_length=1)),
                ('state', models.CharField(max_length=2)),
                ('next_election', models.CharField(max_length=50)),
                ('total_votes', models.IntegerField()),
                ('missed_votes', models.IntegerField()),
                ('total_present', models.IntegerField()),
                ('missed_votes_pct', senate.models.PercentField(decimal_places=2, max_digits=4)),
                ('votes_with_party_pct', senate.models.PercentField(decimal_places=2, max_digits=4)),
                ('votes_against_party_pct', senate.models.PercentField(decimal_places=2, max_digits=4)),
                ('office', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('fax', models.CharField(max_length=12)),
                ('url', models.URLField()),
                ('contact_form', models.URLField()),
                ('source_id', models.CharField(max_length=7)),
                ('source_uri', models.URLField()),
                ('source_last_updated', models.DateTimeField()),
                ('source_last_checked', models.DateTimeField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
